// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExchangeTrafik.Models
{
    public partial class User
    {
        public int ID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public byte? Age { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
    }
}